# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Defining hardware parameters for the vm
  config.vm.provider "virtualbox" do |v|
      v.memory = {{cookiecutter.vm_ram}}
      v.cpus = {{cookiecutter.vm_cpus}}
  end

  config.vm.define "{{cookiecutter.vm_name}}", autostart: false do |machine|
      machine.vm.box = "{{cookiecutter.box}}"
      machine.vm.hostname = "{{cookiecutter.machine_hostname}}"
      machine.vm.network "forwarded_port", guest: {{cookiecutter.forwarded_guest_port}}, host: {{cookiecutter.forwarded_host_port}}
      # set a bridged interface in the VM
      # machine.vm.network "public_network", bridge: "eth0"
      machine.vm.network "private_network", ip: "{{cookiecutter.private_ip}}"
      machine.vm.provision :ansible do |ansible|
            ansible.playbook = "{{cookiecutter.ansible_playbook}}"
            ansible.inventory_path = "{{cookiecutter.ansible_inventory_path}}"
            ansible.host_key_checking = "{{cookiecutter.ansible_host_key_checking}}"
            ansible.verbose = "{{cookiecutter.ansible_verbosity_level}}"
      end
  end
end
