Vagrant.configure("2") do |config|

  # Defining hardware parameters for the vm
  config.vm.provider "virtualbox" do |v|
      v.memory = {{cookiecutter.vm_ram}}
      v.cpus = {{cookiecutter.vm_cpus}}
  end

  config.vm.define "{{cookiecutter.vm_name}}", autostart: false do |machine|
      machine.vm.box = "{{cookiecutter.vm_box}}"
      machine.vm.hostname = "{{cookiecutter.vm_hostname}}"
      # set a bridged interface in the VM
      # machine.vm.network "public_network", bridge: "eth0"
      machine.vm.network "private_network", ip: "{{cookiecutter.private_ip}}"
      machine.vm.provision :ansible do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.inventory_path = "ansible/inventory"
            ansible.host_key_checking = "false"
            ansible.verbose = "v"
      end
  end
end
